@baseUrl = https://localhost:7002

POST {{baseUrl}}/api/auth/register
Accept: application/json
Content-Type: application/json

{
    "email": "admin@mail.ru",
    "userName": "admin",
    "password": "78uiJK!",
    "roleName": "admin"
}

###

POST {{baseUrl}}/api/auth/login
Accept: application/json
Content-Type: application/json

{
    "userName": "admin",
    "password": "78uiJK!"
}

###

POST {{baseUrl}}/api/auth/assignRole
Accept: application/json
Content-Type: application/json

{
    "userName": "test",
    "roleName": "reader"
}
